"""
This file hard-filters certain files from being tested.
This prevents problematic modules, such as those used to instantiate global application
state (celery, some ORM models, their dependents, etc) from running with doctest.
This also prevents pytest from paying attention from autogenerated files (migrations, lexer/parsers.)
"""

bad_substrs = [
    "jasmine-models/migrations",
    "SQLLexer.py",
    "SQLParser.py",
    "SQLParserVisitor.py",
    "SQLParserListener.py",
    # These import global objects or config in a problematic way.
    "jasmine-models/jasmine/models",
    "jasmine-webserver/jasmine/webserver/graphql_models",
    "app.py",
    "tasks.py",
    "jasmine_tracker",
]


def pytest_ignore_collect(path):
    return any(bad_substr in str(path) for bad_substr in bad_substrs)
