[tool.black]
extend-exclude = '''
^.*/(migrations|autogen|SQLLexer.py|SQLParser.py|SQLParserVisitor.py|SQLParserListener.py)$
'''

[tool.isort]
profile = "black"
atomic = true
force_sort_within_sections = true
skip = [
    "migrations",
    "autogen",
    "SQLLexer.py",
    "SQLParser.py",
    "SQLParserVisitor.py",
    "SQLParserListener.py",
]

[tool.mypy]
files = "jasmine-sql/jasmine/,jasmine-webserver/jasmine,jasmine-etl/jasmine/"
ignore_missing_imports = true
exclude = "migrations,autogen,SQLLexer.py,SQLParser.py,SQLParserVisitor.py,SQLParserListener.py"

[tool.pytest.ini_options]
addopts = "--doctest-modules --ignore-glob=jasmine-webserver/migrations/* --ignore-glob=jasmine-webserver/migrations/versions/*.py --ignore=jasmine-sql/jasmine/sql/parser/autogen --ignore=jasmine-sql/jasmine/sql/parser/SQLLexer.py --ignore=jasmine-sql/jasmine/sql/parser/SQLParser.py --ignore=jasmine-sql/jasmine/sql/parser/SQLParserVisitor.py --ignore=jasmine-sql/jasmine/sql/parser/SQLParserListener.py --ignore=jasmine-webserver/jasmine/webserver/models --ignore=jasmine-etl/jasmine/etl/app.py"
doctest_optionflags = "ELLIPSIS"
filterwarnings = "ignore::DeprecationWarning"
