"""Add materialization context column.

Revision ID: 4b6f23a3b894
Revises: c8d7ac3697f5
Create Date: 2021-12-18 23:42:38.636431

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "4b6f23a3b894"
down_revision = "c8d7ac3697f5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("materializations", sa.Column("context", sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("materializations", "context")
    # ### end Alembic commands ###
