"""Add backend type, spec.

Revision ID: d3d4e3d12c7f
Revises: 52df0e51938e
Create Date: 2021-09-16 13:10:24.635217

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "d3d4e3d12c7f"
down_revision = "52df0e51938e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "backends",
        sa.Column("backend_type", sa.Enum("mysql", name="backendtype"), nullable=False),
    )
    op.add_column("backends", sa.Column("spec", sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("backends", "spec")
    op.drop_column("backends", "backend_type")
    # ### end Alembic commands ###
