"""Add user default projects.

Revision ID: 52df0e51938e
Revises: d3b9889927f0
Create Date: 2021-09-14 15:38:32.462885

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "52df0e51938e"
down_revision = "d3b9889927f0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "teams", "name", existing_type=mysql.VARCHAR(length=64), nullable=False
    )
    op.add_column(
        "users", sa.Column("default_project_id", sa.BigInteger(), nullable=True)
    )
    op.create_foreign_key(
        "user_default_project",
        "users",
        "projects",
        ["default_project_id"],
        ["project_id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_default_project", "users", type_="foreignkey")
    op.drop_column("users", "default_project_id")
    op.alter_column(
        "teams", "name", existing_type=mysql.VARCHAR(length=64), nullable=True
    )
    # ### end Alembic commands ###
