"""Genericize queries -> views, where queries are one type of view.

Revision ID: 5fecf4bf9ca5
Revises: d3d4e3d12c7f
Create Date: 2021-09-21 15:09:46.921356

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "5fecf4bf9ca5"
down_revision = "d3d4e3d12c7f"
branch_labels = None
depends_on = None


def confirm(message):
    while True:
        result = input(f"{message} Continue? [yN] ")
        if result in "yY":
            return
        elif result in "nN":
            raise RuntimeError("User aborted operation.")
        else:
            print(f"Invalid input {result}, please respond with 'y' or 'n'.")


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    confirm("This migration just kills all data and recreates the schema.")
    op.create_table(
        "views",
        sa.Column("view_id", sa.BigInteger(), nullable=False),
        sa.Column("view_type", sa.Enum("query", name="viewtype"), nullable=False),
        sa.Column("spec", sa.JSON(), nullable=False),
        sa.Column("path", sa.String(length=256), nullable=False),
        sa.Column("project_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.project_id"],
        ),
        sa.PrimaryKeyConstraint("view_id"),
        sa.UniqueConstraint("project_id", "path"),
    )
    op.drop_index("project_id", table_name="queries")
    op.drop_table("queries")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    confirm("This migration just kills all data and recreates the schema.")
    op.create_table(
        "queries",
        sa.Column("query_id", mysql.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("query_text", mysql.TEXT(), nullable=False),
        sa.Column("path", mysql.VARCHAR(length=256), nullable=False),
        sa.Column("project_id", mysql.BIGINT(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.project_id"], name="queries_ibfk_1"
        ),
        sa.PrimaryKeyConstraint("query_id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index("project_id", "queries", ["project_id", "path"], unique=False)
    op.drop_table("views")
    # ### end Alembic commands ###
